const ccirs = [
  {
    id: 'CCIR-1',
    title: 'Is Russia moving from routine posture to operational preparation against the Baltic region?',
    titleEt: 'Kas Venemaa liigub rutiinsest paiknemisest operatiivse ettevalmistuse faasi Balti regiooni vastu?',
    owner: 'Strategic Warning Cell', priority: 'critical', decisionPoint: 'DP-1 Baltic posture decision',
    supportedDecision: 'Whether to raise Baltic ISR priority, prepare branch plan B and brief political-military leadership.',
    supportedDecisionEt: 'Kas tõsta Balti ISR prioriteeti, valmistada ette branch plan B ja teavitada poliitilis-sõjalist juhtimist.',
    description: 'Tracks force posture, logistics, C2/EW, air, maritime and enabling movements that would change warning timelines for Estonia, Latvia, Lithuania and the Baltic Sea approaches.',
    descriptionEt: 'Jälgib jõudude paiknemist, logistikat, C2/EW-d, õhu-, mere- ja võimaldavaid liikumisi, mis muudaksid Eesti, Läti, Leedu ja Balti mere lähenemiste hoiatustähtaegu.',
    ifAndThen: { if: 'PIR-1 and PIR-2 reach Partial or Answered', and: 'FFIR-1 confirms available collection capacity', then: 'Increase collection priority on NAI-03, NAI-04, NAI-06, NAI-07 and prepare Baltic posture brief.' },
    recommendation: 'Maintain baseline posture until at least two operational PIRs become Partial. Then increase NAI-focused collection and prepare DP-1 briefing.',
    recommendationEt: 'Hoia baasvalmidust, kuni vähemalt kaks operatiivset PIR-i muutuvad Partial tasemele. Seejärel suurenda NAI-põhist kogumist ja valmista ette DP-1 ülevaade.',
    ltiov: '18h'
  },
  {
    id: 'CCIR-2',
    title: 'Is a Baltic-focused pretext, hybrid or information operation pattern forming?',
    titleEt: 'Kas kujuneb Balti-keskne ettekääne, hübriid- või infooperatsiooni muster?',
    owner: 'Information Environment Desk', priority: 'high', decisionPoint: 'DP-2 Strategic communication and resilience response',
    supportedDecision: 'Whether to activate counter-narrative monitoring, public affairs coordination, cyber resilience and diplomatic warning products.',
    supportedDecisionEt: 'Kas aktiveerida vastunarratiivi seire, avaliku kommunikatsiooni koordineerimine, küberkerksus ja diplomaatilised hoiatusproduktid.',
    description: 'Tracks narrative preparation, connectivity disruption, cyber/GPS anomalies, coercive signaling and politically useful provocation framing.',
    descriptionEt: 'Jälgib narratiivset ettevalmistust, ühenduvushäireid, küber/GPS anomaaliaid, survet ja poliitiliselt kasulikku provokatsiooniraamistust.',
    ifAndThen: { if: 'PIR-5 or PIR-6 is Partial/Answered', and: 'FFIR-2 confirms communications capacity', then: 'Recommend coordinated strategic communication and cyber resilience response.' },
    recommendation: 'Prioritize NAI-08 and NAI-10 when Baltic narratives combine with disruption indicators.',
    recommendationEt: 'Prioriseeri NAI-08 ja NAI-10, kui Balti narratiivid kattuvad häirenäitajatega.',
    ltiov: '24h'
  },
  {
    id: 'CCIR-3',
    title: 'Are Belarus, Kaliningrad and the north-western flank becoming synchronized for regional pressure?',
    titleEt: 'Kas Valgevene, Kaliningrad ja loodeflank muutuvad regionaalse surve jaoks sünkroniseerituks?',
    owner: 'Regional Fusion Cell', priority: 'high', decisionPoint: 'DP-3 Regional escalation posture',
    supportedDecision: 'Whether to shift regional collection and warning focus toward Kaliningrad, Belarus, Suwałki and Baltic air-sea approaches.',
    supportedDecisionEt: 'Kas nihutada regionaalne kogumis- ja hoiatusfookus Kaliningradi, Valgevene, Suwałki ja Balti õhu-mere lähenemistele.',
    description: 'Tracks whether geographically separate indicators align into a coherent Baltic warning picture that affects decision timelines.',
    descriptionEt: 'Jälgib, kas geograafiliselt eraldi näitajad koonduvad ühtseks Balti hoiatuse pildiks, mis mõjutab otsustustähtaegu.',
    ifAndThen: { if: 'PIR-3 and PIR-4 reach Partial or Answered', and: 'FFIR-3 confirms readiness impacts are manageable', then: 'Recommend regional escalation brief and collection synchronization update.' },
    recommendation: 'Prioritize NAI-06, NAI-07, NAI-08 and NAI-09 when Belarus, Kaliningrad and Baltic Sea indicators cluster.',
    recommendationEt: 'Prioriseeri NAI-06, NAI-07, NAI-08 ja NAI-09, kui Valgevene, Kaliningradi ja Balti mere näitajad klasterduvad.',
    ltiov: '12h'
  }
];

const pirs = [
  { id:'PIR-1', ccir:'CCIR-1', title:'Are new manoeuvre, artillery, air defence, EW, engineer or C2 elements appearing on Baltic-facing axes?', titleEt:'Kas Balti suunal ilmuvad uued manööver-, suurtükiväe-, õhutõrje-, EW-, inseneri- või C2 elemendid?', linkedDecision:'DP-1', ltiov:'18h', naiIds:['NAI-03','NAI-04','NAI-07'] },
  { id:'PIR-2', ccir:'CCIR-1', title:'Are logistics, rail, depots, fuel, medical or bridge assets appearing in a way consistent with sustained activity?', titleEt:'Kas logistika, raudtee, laod, kütus, meditsiin või sillavahendid ilmuvad viisil, mis viitab püsivale tegevusele?', linkedDecision:'DP-1', ltiov:'18h', naiIds:['NAI-04','NAI-06','NAI-07','NAI-09'] },
  { id:'PIR-3', ccir:'CCIR-3', title:'Is Kaliningrad, Suwałki or the Baltic air-sea axis showing synchronized pressure indicators?', titleEt:'Kas Kaliningrad, Suwałki või Balti õhu-mere telg näitab sünkroniseeritud surve näitajaid?', linkedDecision:'DP-3', ltiov:'12h', naiIds:['NAI-06','NAI-07','NAI-08'] },
  { id:'PIR-4', ccir:'CCIR-3', title:'Is Belarus or the north-western flank enabling Russian regional operations?', titleEt:'Kas Valgevene või loodeflank võimaldab Venemaa regionaalseid operatsioone?', linkedDecision:'DP-3', ltiov:'12h', naiIds:['NAI-01','NAI-02','NAI-09'] },
  { id:'PIR-5', ccir:'CCIR-2', title:'Are cyber, GPS, drone, airspace, maritime or sabotage indicators clustering in the Baltic warning area?', titleEt:'Kas küber-, GPS-, drooni-, õhuruumi-, merendus- või sabotaažinäitajad klasterduvad Balti hoiatusalas?', linkedDecision:'DP-2', ltiov:'12h', naiIds:['NAI-02','NAI-08','NAI-10'] },
  { id:'PIR-6', ccir:'CCIR-2', title:'Is a coherent Baltic-focused pretext narrative forming?', titleEt:'Kas kujuneb ühtne Balti-keskne ettekäändenarratiiv?', linkedDecision:'DP-2', ltiov:'24h', naiIds:['NAI-03','NAI-06','NAI-10'] }
];

const indicators = [
  { id:'IND-1.1', pir:'PIR-1', weight:3, status:'unanswered', description:'Forward appearance or movement of manoeuvre, artillery, air defence, EW, engineer or C2 assets.', descriptionEt:'Manööver-, suurtükiväe-, õhutõrje-, EW-, inseneri- või C2 vahendite ettepoole ilmumine või liikumine.', confirms:'Operational preparation COA', negates:'Routine training-only COA', keywords:['brigade','division','battalion','troop','unit','deployment','redeploy','artillery','air defence','air defense','ew','electronic warfare','engineer','command','c2','pskov','luga','narva','ivangorod','kaliningrad','chernyakhovsk','baltiysk'] },
  { id:'IND-1.2', pir:'PIR-1', weight:2, status:'unanswered', description:'Command, communications, radar, ISR or jamming assets increase near Baltic-facing areas.', descriptionEt:'Juhtimis-, side-, radari-, ISR- või segamisvahendid sagenevad Balti suuna lähedal.', confirms:'Coordinated posture development', negates:'Isolated tactical movement', keywords:['command post','communications','radar','isr','surveillance','reconnaissance','gps jamming','jamming','st petersburg','gulf of finland','kola','murmansk'] },
  { id:'IND-2.1', pir:'PIR-2', weight:3, status:'unanswered', description:'Fuel, ammunition, medical, maintenance, bridge, rail or depot support moves forward.', descriptionEt:'Kütus, laskemoon, meditsiin, hooldus, sillavahendid, raudtee või laotoetus liigub ettepoole.', confirms:'Sustained operation preparation', negates:'Short-duration exercise', keywords:['fuel','ammunition','ammo','depot','hospital','medical','bridge','rail','railway','logistics','maintenance','supply','baranovichi','brest','grodno'] },
  { id:'IND-3.1', pir:'PIR-3', weight:3, status:'unanswered', description:'Kaliningrad, Suwałki, Baltic Sea or Gulf of Finland indicators align across land, air and maritime domains.', descriptionEt:'Kaliningradi, Suwałki, Balti mere või Soome lahe näitajad joonduvad maa-, õhu- ja meredomeenides.', confirms:'Regional synchronization', negates:'Single-axis pressure', keywords:['kaliningrad','suwalki','suwałki','baltic sea','gulf of finland','gulf of riga','baltiysk','ship','vessel','airspace','aircraft','s-400','missile'] },
  { id:'IND-4.1', pir:'PIR-4', weight:3, status:'unanswered', description:'Belarus, Kola/Murmansk or north-western flank appears in enabling political or operational context.', descriptionEt:'Valgevene, Kola/Murmansk või loodeflank ilmub võimaldavas poliitilises või operatiivses kontekstis.', confirms:'Flank enabling shift', negates:'Unrelated domestic development', keywords:['belarus','belarusian','minsk','grodno','brest','baranovichi','union state','joint exercise','kola','murmansk','northern fleet','north-western','western military district'] },
  { id:'IND-5.1', pir:'PIR-5', weight:3, status:'unanswered', description:'Cyber, GPS, drone, airspace, maritime, cable or sabotage indicators cluster in time and geography.', descriptionEt:'Küber-, GPS-, drooni-, õhuruumi-, merendus-, kaabli- või sabotaažinäitajad klasterduvad ajas ja ruumis.', confirms:'Hybrid pressure pattern', negates:'Unrelated incidents', keywords:['gps','jamming','cyber','drone','uav','sabotage','airspace','maritime','vessel','pipeline','cable','telecom','ooni','outage','network'] },
  { id:'IND-6.1', pir:'PIR-6', weight:3, status:'unanswered', description:'Narrative links Baltic states, NATO, minorities, drones, religion, border incidents or provocation frames.', descriptionEt:'Narratiiv seob Balti riigid, NATO, vähemused, droonid, religiooni, piiriintsidendid või provokatsiooniraamid.', confirms:'Pretext building', negates:'Generic propaganda noise', keywords:['provocation','nato','baltic states','estonia','latvia','lithuania','minorities','russian speakers','false flag','pretext','narrative','border incident','russophobia'] }
];

const collectionSirs = [
  { id:'CSIR-1.1.1', indicator:'IND-1.1', pir:'PIR-1', requirement:'Detect new manoeuvre, artillery, air defence, EW, engineer or C2 assets in the Narva/Ivangorod axis.', requirementEt:'Tuvasta uued manööver-, suurtükiväe-, õhutõrje-, EW-, inseneri- või C2 vahendid Narva/Ivangorodi teljel.', nai:'NAI-03', timeWindow:'Next 18h', ltiov:'18h', collector:'OSINT/RSS + official statements + analyst review', reportingCriteria:'Report when credible feeds connect military asset movement with Narva, Ivangorod or Estonia north-east.', status:'unanswered' },
  { id:'CSIR-1.1.2', indicator:'IND-1.1', pir:'PIR-1', requirement:'Detect staging, movement or support elements in the Pskov/Luga approach.', requirementEt:'Tuvasta koondumine, liikumine või toetus Pihkva/Luga lähenemisel.', nai:'NAI-04', timeWindow:'Next 18h', ltiov:'18h', collector:'OSINT/RSS + ISW + regional media', reportingCriteria:'Report if Pskov, Luga or north-western flank terms co-occur with units, C2 or movement.', status:'unanswered' },
  { id:'CSIR-1.1.3', indicator:'IND-1.1', pir:'PIR-1', requirement:'Detect force movement, border pressure or support activity around Daugavpils and Latvia east.', requirementEt:'Tuvasta jõuliikumine, piirisurve või toetus Daugavpilsi ja Ida-Läti piirkonnas.', nai:'NAI-05', timeWindow:'Next 18h', ltiov:'18h', collector:'OSINT/RSS + Latvian/regional media + official alerts', reportingCriteria:'Report when Daugavpils, eastern Latvia, border, unit movement or support terms co-occur.', status:'unanswered' },
  { id:'CSIR-1.2.1', indicator:'IND-1.2', pir:'PIR-1', requirement:'Detect command, radar, ISR or jamming activity around St Petersburg / Gulf of Finland.', requirementEt:'Tuvasta juhtimis-, radari-, ISR- või segamistegevus Peterburi / Soome lahe piirkonnas.', nai:'NAI-02', timeWindow:'Next 12h', ltiov:'12h', collector:'OSINT/RSS + cyber/EW cues + official alerts', reportingCriteria:'Report when C2/EW/ISR terms align with St Petersburg, Gulf of Finland or Leningrad Oblast.', status:'unanswered' },
  { id:'CSIR-2.1.1', indicator:'IND-2.1', pir:'PIR-2', requirement:'Detect ammunition, fuel, depot, rail, bridge or medical support movement around Suwałki / Grodno / Brest.', requirementEt:'Tuvasta laskemoona, kütuse, ladude, raudtee, sillavahendite või meditsiinitoe liikumine Suwałki / Grodno / Bresti piirkonnas.', nai:'NAI-06', timeWindow:'Next 18h', ltiov:'18h', collector:'OSINT/RSS + rail/local reporting + analyst review', reportingCriteria:'Report when logistics objects and Suwałki, Grodno or Brest geography co-occur.', status:'unanswered' },
  { id:'CSIR-2.1.2', indicator:'IND-2.1', pir:'PIR-2', requirement:'Detect logistics or sustainment indicators in Belarus staging areas.', requirementEt:'Tuvasta logistika või püsivtegevuse näitajad Valgevene koondumispiirkondades.', nai:'NAI-09', timeWindow:'Next 18h', ltiov:'18h', collector:'OSINT/RSS + official statements + regional media', reportingCriteria:'Report when Belarus locations co-occur with rail, depots, fuel, medical or exercises.', status:'unanswered' },
  { id:'CSIR-3.1.1', indicator:'IND-3.1', pir:'PIR-3', requirement:'Detect A2/AD, air, naval or missile posture changes in Kaliningrad and Baltiysk.', requirementEt:'Tuvasta A2/AD, õhu-, mere- või raketihoiakumuutused Kaliningradis ja Baltiyskis.', nai:'NAI-07', timeWindow:'Next 12h', ltiov:'12h', collector:'NATO/official feeds + OSINT/RSS + maritime/aviation monitoring', reportingCriteria:'Report when Kaliningrad, Baltiysk or Chernyakhovsk co-occurs with S-400, missile, aircraft, ship or alerting language.', status:'unanswered' },
  { id:'CSIR-3.1.2', indicator:'IND-3.1', pir:'PIR-3', requirement:'Detect maritime, airspace, cable or route disruptions in the Baltic Sea and Gulf of Riga.', requirementEt:'Tuvasta mere-, õhuruumi-, kaabli- või marsruudihäired Balti merel ja Liivi lahes.', nai:'NAI-08', timeWindow:'Next 12h', ltiov:'12h', collector:'Cyber/maritime/aviation feeds + RSS + local media', reportingCriteria:'Report when maritime, airspace, cable or GPS terms co-occur with Baltic Sea, Gulf of Riga or regional coastal states.', status:'unanswered' },
  { id:'CSIR-4.1.1', indicator:'IND-4.1', pir:'PIR-4', requirement:'Detect Northern Fleet / Kola / Murmansk activity that affects Baltic or NATO northern flank posture.', requirementEt:'Tuvasta Põhjalaevastiku / Kola / Murmanski tegevus, mis mõjutab Balti või NATO põhjaflanki.', nai:'NAI-01', timeWindow:'Next 24h', ltiov:'24h', collector:'ISW/NATO/official feeds + OSINT', reportingCriteria:'Report when Kola, Murmansk or Northern Fleet co-occurs with exercise, movement, access or alert posture.', status:'unanswered' },
  { id:'CSIR-4.1.2', indicator:'IND-4.1', pir:'PIR-4', requirement:'Detect Belarusian political, base, airfield or border-access enabling actions.', requirementEt:'Tuvasta Valgevene poliitilised, baasi-, lennuvälja- või piiriligipääsu võimaldavad sammud.', nai:'NAI-09', timeWindow:'Next 12h', ltiov:'12h', collector:'Official statements + RSS + OSINT', reportingCriteria:'Report when access/base/border/airfield language co-occurs with Belarus or Russia.', status:'unanswered' },
  { id:'CSIR-5.1.1', indicator:'IND-5.1', pir:'PIR-5', requirement:'Detect GPS jamming, cyber, drone, airspace or sabotage events against Baltic capitals and critical nodes.', requirementEt:'Tuvasta GPS-segamine, küber-, drooni-, õhuruumi- või sabotaažisündmused Balti pealinnade ja kriitiliste sõlmede vastu.', nai:'NAI-10', timeWindow:'Next 12h', ltiov:'12h', collector:'OONI/cyber feeds + local media + official alerts', reportingCriteria:'Report when disruption or cyber terms co-occur with Tallinn, Riga, Vilnius or Baltic critical infrastructure.', status:'unanswered' },
  { id:'CSIR-5.1.2', indicator:'IND-5.1', pir:'PIR-5', requirement:'Detect hybrid disruption indicators around Baltic maritime and air approaches.', requirementEt:'Tuvasta hübriidhäirete näitajad Balti merelistes ja õhulähenemistes.', nai:'NAI-08', timeWindow:'Next 12h', ltiov:'12h', collector:'Maritime/aviation/cyber feeds + RSS', reportingCriteria:'Report if GPS, drone, vessel, airspace, cable or sabotage terms appear with Baltic Sea geography.', status:'unanswered' },
  { id:'CSIR-6.1.1', indicator:'IND-6.1', pir:'PIR-6', requirement:'Detect Baltic-specific pretext narratives around NATO, minorities, border incidents or alleged provocations.', requirementEt:'Tuvasta Balti-spetsiifilised ettekäändenarratiivid NATO, vähemuste, piiriintsidentide või väidetavate provokatsioonide ümber.', nai:'NAI-10', timeWindow:'Next 24h', ltiov:'24h', collector:'Media monitoring + GDELT-style narrative cues + RSS', reportingCriteria:'Report when Baltic geography and pretext/provocation language appear together in credible or high-volume feeds.', status:'unanswered' }
];

const ffirs = [
  { id:'FFIR-1', ccir:'CCIR-1', question:'Do friendly collection assets have capacity to increase monitoring on NAI-03, NAI-04, NAI-06 and NAI-07?', owner:'Operations / Collection Manager', status:'not assessed', evidenceIds:[] },
  { id:'FFIR-2', ccir:'CCIR-2', question:'Do cyber, public affairs and diplomatic channels have prepared response products for Baltic disruption or narrative escalation?', owner:'Cyber / Strategic Communications', status:'not assessed', evidenceIds:[] },
  { id:'FFIR-3', ccir:'CCIR-3', question:'Can regional readiness posture absorb additional monitoring or alerting tasks for Kaliningrad, Belarus and Suwałki?', owner:'J3 / Regional Desk', status:'not assessed', evidenceIds:[] }
];

const nais = [
  { id:'NAI-01', name:'Kola / Murmansk / Northern Fleet', type:'northern flank', country:'Russia', lat:68.97, lon:33.08, radiusKm:220, linkedPirs:['PIR-4'], collectionSirIds:['CSIR-4.1.1'], focus:'Northern Fleet and Kola Peninsula activity affecting the wider NATO northern flank.' },
  { id:'NAI-02', name:'St Petersburg / Gulf of Finland', type:'air-maritime / C2-EW', country:'Russia / Finland / Estonia', lat:59.93, lon:30.36, radiusKm:190, linkedPirs:['PIR-1','PIR-5'], collectionSirIds:['CSIR-1.2.1'], focus:'C2, radar, ISR, EW and air-maritime activity around St Petersburg and the Gulf of Finland.' },
  { id:'NAI-03', name:'Narva / Ivangorod / Estonia NE border', type:'land border', country:'Estonia / Russia', lat:59.38, lon:28.20, radiusKm:90, linkedPirs:['PIR-1','PIR-6'], collectionSirIds:['CSIR-1.1.1'], focus:'Baltic land-border warning indicators and local provocation potential.' },
  { id:'NAI-04', name:'Pskov / Luga approach', type:'land approach', country:'Russia', lat:57.82, lon:28.33, radiusKm:170, linkedPirs:['PIR-1','PIR-2'], collectionSirIds:['CSIR-1.1.2'], focus:'Force posture, staging and support movements from the north-western Russian approach.' },
  { id:'NAI-05', name:'Latvia eastern border / Daugavpils axis', type:'land border', country:'Latvia / Belarus / Russia', lat:55.87, lon:26.54, radiusKm:130, linkedPirs:['PIR-1','PIR-2'], collectionSirIds:['CSIR-1.1.2','CSIR-2.1.2'], focus:'Eastern Latvia access, Daugavpils axis and cross-border pressure indicators.' },
  { id:'NAI-06', name:'Suwałki / Grodno / Brest corridor', type:'land corridor', country:'Poland / Lithuania / Belarus', lat:54.10, lon:22.93, radiusKm:160, linkedPirs:['PIR-2','PIR-3','PIR-6'], collectionSirIds:['CSIR-2.1.1'], focus:'Sustainment, movement and regional synchronization indicators around the Suwałki corridor.' },
  { id:'NAI-07', name:'Kaliningrad / Baltiysk / Chernyakhovsk', type:'land-air-sea', country:'Russia', lat:54.71, lon:20.45, radiusKm:145, linkedPirs:['PIR-1','PIR-2','PIR-3'], collectionSirIds:['CSIR-3.1.1'], focus:'Kaliningrad A2/AD, naval, air and ground posture indicators.' },
  { id:'NAI-08', name:'Baltic Sea / Gulf of Riga / maritime axis', type:'maritime-air', country:'Baltic Sea', lat:57.20, lon:21.70, radiusKm:420, linkedPirs:['PIR-3','PIR-5'], collectionSirIds:['CSIR-3.1.2','CSIR-5.1.2'], focus:'Maritime, airspace, cable, GPS and hybrid disruption indicators across Baltic approaches.' },
  { id:'NAI-09', name:'Belarus staging / Minsk-Baranovichi-Brest', type:'land / political enabling', country:'Belarus', lat:53.90, lon:27.56, radiusKm:260, linkedPirs:['PIR-2','PIR-4'], collectionSirIds:['CSIR-2.1.2','CSIR-4.1.2'], focus:'Belarusian staging, airfield, rail, exercise and political enabling indicators.' },
  { id:'NAI-10', name:'Baltic capitals / cyber-information nodes', type:'cyber-information', country:'Estonia / Latvia / Lithuania', lat:56.95, lon:24.11, radiusKm:430, linkedPirs:['PIR-5','PIR-6'], collectionSirIds:['CSIR-5.1.1','CSIR-6.1.1'], focus:'Tallinn, Riga, Vilnius and critical information/cyber nodes for hybrid and narrative indicators.' }
];

const mapCountries = [
  ['Portugal','Lisbon',38.72,-9.14],['Spain','Madrid',40.42,-3.70],['France','Paris',48.86,2.35],['Ireland','Dublin',53.35,-6.26],['United Kingdom','London',51.51,-0.13],['Belgium','Brussels',50.85,4.35],['Netherlands','Amsterdam',52.37,4.90],['Luxembourg','Luxembourg',49.61,6.13],['Germany','Berlin',52.52,13.40],['Denmark','Copenhagen',55.68,12.57],['Norway','Oslo',59.91,10.75],['Sweden','Stockholm',59.33,18.07],['Finland','Helsinki',60.17,24.94],['Estonia','Tallinn',59.44,24.75],['Latvia','Riga',56.95,24.11],['Lithuania','Vilnius',54.69,25.28],['Poland','Warsaw',52.23,21.01],['Czechia','Prague',50.08,14.44],['Austria','Vienna',48.21,16.37],['Slovakia','Bratislava',48.15,17.11],['Hungary','Budapest',47.50,19.04],['Slovenia','Ljubljana',46.06,14.51],['Croatia','Zagreb',45.81,15.98],['Italy','Rome',41.90,12.50],['Malta','Valletta',35.90,14.51],['Greece','Athens',37.98,23.73],['Cyprus','Nicosia',35.19,33.38],['Bulgaria','Sofia',42.70,23.32],['Romania','Bucharest',44.43,26.10],['Moldova','Chisinau',47.01,28.86],['Ukraine','Kyiv',50.45,30.52],['Belarus','Minsk',53.90,27.56],['Russia','Moscow',55.76,37.62],['Türkiye','Ankara',39.93,32.86]
].map(([country, capital, lat, lon]) => ({ country, capital, lat, lon }));

const seriousIncidentReports = [
  { id:'SIRPT-1', type:'Own-force casualty / loss', trigger:'Fatality, severe injury, missing personnel or captured personnel.', action:'Notify command chain and prepare formal incident report.' },
  { id:'SIRPT-2', type:'Civilian harm or politically sensitive incident', trigger:'Civilian casualties, major infrastructure damage or politically sensitive event.', action:'Notify command, legal and public affairs channels.' },
  { id:'SIRPT-3', type:'Base / facility attack', trigger:'Attack, sabotage, intrusion or severe disruption affecting a friendly facility.', action:'Activate incident reporting and force protection review.' },
  { id:'SIRPT-4', type:'Major cyber or communications outage', trigger:'Severe loss of command, control or communications capacity.', action:'Notify cyber / C2 owners and escalate to operational leadership.' }
];

const redFlags = [
  { id:'RF-1', level:'red', weight:20, name:'Synchronized force build-up on Baltic-facing axes', nameEt:'Jõudude sünkroniseeritud koondamine Balti suunal', description:'Multiple force elements, command and support indicators appear together in NAI-02/03/04/07.', descriptionEt:'Mitmed jõu-, juhtimis- ja toetusnäitajad ilmuvad koos NAI-02/03/04/07 aladel.' },
  { id:'RF-2', level:'red', weight:18, name:'Operational logistics forward movement', nameEt:'Operatiivse logistika etteviimine', description:'Support assets suggest preparation for sustained activity rather than routine movement.', descriptionEt:'Toetusvahendid viitavad püsiva tegevuse ettevalmistusele, mitte tavaliikumisele.' },
  { id:'RF-3', level:'orange', weight:14, name:'Baltic-focused pretext narrative', nameEt:'Balti-keskne ettekäändenarratiiv', description:'Narratives cohere around Baltic targets, NATO reaction, minorities or provocation frames.', descriptionEt:'Narratiivid koonduvad Balti sihtmärkide, NATO reaktsiooni, vähemuste või provokatsiooniraamide ümber.' },
  { id:'RF-4', level:'orange', weight:14, name:'Hybrid incident clustering', nameEt:'Hübriidintsidentide klaster', description:'Cyber, drone, airspace, sabotage or communications anomalies appear in the same warning window.', descriptionEt:'Küber-, drooni-, õhuruumi-, sabotaaži- või sideanomaaliad ilmuvad samas hoiatusaknas.' },
  { id:'RF-5', level:'orange', weight:10, name:'Belarus / Kaliningrad / north-west enabling shift', nameEt:'Valgevene / Kaliningradi / loodesuuna võimaldav nihe', description:'Belarus, Kaliningrad or the north-western flank appears in an enabling political or operational role.', descriptionEt:'Valgevene, Kaliningrad või loodesuund ilmub võimaldavas poliitilises või operatiivses rollis.' },
  { id:'RF-6', level:'yellow', weight:8, name:'Air / maritime provocation pattern', nameEt:'Õhu- / merelise provokatsiooni muster', description:'Airspace or maritime pressure indicators become more visible.', descriptionEt:'Õhuruumi või merelise surve näitajad muutuvad nähtavamaks.' },
  { id:'RF-7', level:'yellow', weight:8, name:'Drone / ISR targeting acceleration', nameEt:'Drooni / ISR sihtmärgistamise kiirenemine', description:'Drone, ISR or targeting-related objects and reports increase.', descriptionEt:'Drooni, ISR-i või sihtmärgistamisega seotud objektid ja raportid sagenevad.' },
  { id:'RF-8', level:'yellow', weight:8, name:'Internal mobilisation and coercion pressure', nameEt:'Sisemine mobilisatsiooni- ja survekasv', description:'Recruitment, mobilisation, information control or coercive signs intensify.', descriptionEt:'Värbamine, mobilisatsioon, infokontroll või surve tunnused tugevnevad.' }
];

const sourceAssets = [
  { id:'isw', name:'ISW daily assessments', category:'Operational', cadence:'Daily', period:'Public campaign updates', use:'Operational-level text, setting conditions, mobilisation, pressure and troop posture updates.', whyUseful:'Good for daily campaign assessment and force posture monitoring.', url:'https://www.understandingwar.org/', coveredNaiIds:['NAI-01','NAI-02','NAI-03','NAI-04','NAI-05','NAI-06','NAI-07','NAI-08','NAI-09','NAI-10'] },
  { id:'nato', name:'NATO / SHAPE', category:'Official', cadence:'Daily', period:'Public media and statements', use:'NATO posture, reassurance, deterrence and readiness related official updates.', whyUseful:'Good for deterrence and allied posture visibility.', url:'https://www.nato.int/', coveredNaiIds:['NAI-01','NAI-02','NAI-03','NAI-04','NAI-05','NAI-06','NAI-07','NAI-08','NAI-09','NAI-10'] },
  { id:'vla', name:'Estonian Foreign Intelligence Service', category:'Official', cadence:'Periodic', period:'Public reports and articles', use:'Estonian strategic warning and threat framing.', whyUseful:'Relevant national strategic warning perspective.', url:'https://www.valisluureamet.ee/en.html', coveredNaiIds:['NAI-02','NAI-03','NAI-04','NAI-10'] },
  { id:'ooni', name:'OONI network observations', category:'Cyber', cadence:'Daily', period:'Public measurement data', use:'Network anomalies, censorship indicators and possible internet disruptions.', whyUseful:'Good for cyber and connectivity anomalies.', url:'https://explorer.ooni.org/', coveredNaiIds:['NAI-10'] },
  { id:'gdelt', name:'GDELT', active:false, category:'Global media & events', cadence:'Continuous', period:'API / event stream', use:'Tracks global media flows, events, narratives, locations and entities.', whyUseful:'Strong source for media and event monitoring.', url:'https://www.gdeltproject.org/', coveredNaiIds:['NAI-01','NAI-02','NAI-03','NAI-04','NAI-05','NAI-06','NAI-07','NAI-08','NAI-09','NAI-10'] },
  { id:'acled', name:'ACLED', active:false, category:'Conflict data', cadence:'Frequent', period:'Structured conflict event data', use:'Structured conflict, protest and political violence data.', whyUseful:'Excellent for geographic and temporal conflict analysis.', url:'https://acleddata.com/', coveredNaiIds:['NAI-06','NAI-09','NAI-10'] },
  { id:'reliefweb', name:'ReliefWeb', active:false, category:'Humanitarian', cadence:'Continuous', period:'API / reports', use:'Crisis, disaster, humanitarian situation and report tracking.', whyUseful:'Good for humanitarian context and crisis reporting.', url:'https://reliefweb.int/', coveredNaiIds:['NAI-09','NAI-10'] },
  { id:'hdx', name:'HDX / HDX HAPI', active:false, category:'Humanitarian data', cadence:'Frequent', period:'Structured datasets', use:'Country profiles and humanitarian context datasets.', whyUseful:'Useful for contextual enrichment around crises.', url:'https://data.humdata.org/', coveredNaiIds:['NAI-09','NAI-10'] },
  { id:'opensanctions', name:'OpenSanctions', active:false, category:'Sanctions / PEP', cadence:'Frequent', period:'Entity graph / API', use:'Sanctions, PEP, companies and entity relationships.', whyUseful:'Useful for sanctions and exposure enrichment.', url:'https://www.opensanctions.org/', coveredNaiIds:['NAI-09','NAI-10'] },
  { id:'postimees', name:'Postimees RSS', category:'Media', cadence:'Hourly', period:'RSS / public news', use:'Estonian news coverage for local security, politics and society.', whyUseful:'Good for domestic narratives and fast local developments.', url:'https://www.postimees.ee/rss', coveredNaiIds:['NAI-03','NAI-10'] },
  { id:'delfi', name:'Delfi RSS', category:'Media', cadence:'Hourly', period:'RSS / public news', use:'Large Estonian media source for domestic and regional developments.', whyUseful:'Good for rapid domestic coverage and narrative tracking.', url:'https://www.delfi.ee/rss', coveredNaiIds:['NAI-03','NAI-10'] },
  { id:'vm', name:'Eesti Välisministeerium', category:'Official', cadence:'Frequent', period:'News / statements', use:'Official Estonian foreign policy and diplomatic statements.', whyUseful:'Useful for official policy position and diplomatic response tracking.', url:'https://www.vm.ee/en', coveredNaiIds:['NAI-10'] }
];

const defaultAssessment = {
  score: 0, label: 'GREEN', confidenceScore: 1,
  summary: 'Baseline: no active red flags are currently derived from collected signals.',
  summaryEt: 'Baasjoon: kogutud signaalidest ei tuletata praegu aktiivseid punaseid lippe.',
  updatedAt: new Date().toISOString(), activeFlagIds: [], rationale: ['No active red flags derived from current signals.'], rationaleEt: ['Kogutud signaalidest ei tuletata praegu aktiivseid punaseid lippe.'],
  ccirAssessments: [], pirAssessments: [], indicatorAssessments: [], collectionSirAssessments: [], ffirAssessments: []
};

const sirs = collectionSirs.map((item) => ({ id:item.id.replace('CSIR','SIR'), pir:item.pir, indicator:item.indicator, text:item.requirement, textEt:item.requirementEt || item.requirement }));

module.exports = { ccirs, pirs, indicators, collectionSirs, sirs, ffirs, nais, mapCountries, seriousIncidentReports, redFlags, sourceAssets, defaultAssessment };
